detectors:
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    exclude:
      - IndieWeb::Endpoints::Client#response
  UtilityFunction:
    exclude:
      - FixtureHelpers#read_fixture

exclude_paths:
  - vendor/
