detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    exclude:
      - FixtureHelpers#read_fixture
      - IndieWeb::Endpoints::Services::ResponseBodyParserService#parse
      - IndieWeb::Endpoints::Services::ResponseHeadersParserService#parse

exclude_paths:
  - vendor/
